---
- hosts: web
  become: true
  tasks:
    - name: deploy to tomcat server
      copy:
        src: /var/lib/jenkins/workspace/Ansible-Tomcat/hello-world-new/webapp/target/webapp.war
        dest: /usr/share/tomcat9       
